# Generated by Django 5.0.6 on 2024-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_xlsx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='subir_archivo',
            field=models.FileField(upload_to='./archivos_csv/'),
        ),
    ]
