# Generated by Django 5.0.6 on 2024-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_xlsx', '0002_alter_archivo_subir_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='subir_archivo',
            field=models.FileField(upload_to='./csv_xlsx/archivos_csv/'),
        ),
    ]
